apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook:leader-election
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: phonebook:leader-election
subjects:
- kind: ServiceAccount
  name: phonebook-controller
  namespace: {{ .Release.Namespace }}

