apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}

  name: phonebook:controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: phonebook:controller
subjects:
- kind: ServiceAccount
  name: phonebook-controller
  namespace: {{ .Release.Namespace }}
