apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: phonebook
    {{- include "operator.labels" . | nindent 4 }}
  name: phonebook-manager
  namespace: {{ .Release.Namespace }}

