apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonebook-controller
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: phonebook-manager
    {{- include "operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: phonebook-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: phonebook-manager
        {{- include "operator.labels" . | nindent 8 }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                    - arm64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - command:
        - /manager
        args:
          - --leader-elect
          - --health-probe-bind-address=:8081
        image: {{ default "github.com/pier-oliviert/phonebook:0.1" .Values.manager.image }} 
        name: manager
        env:
        {{- range .Values.manager.env }}
          - name: {{ .name | quote }}
            value: {{ .value | quote }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        {{- if .Values.manager.providerSecrets }}
          - name: provider-secrets
            mountPath: /var/run/configs/provider/
            readOnly: true
        {{- end }}
      serviceAccountName: phonebook-manager
      terminationGracePeriodSeconds: 10
      volumes:
      {{- if .Values.manager.providerSecrets }}
        - name: provider-secrets
          secret:
            secretName: {{ .Values.manager.providerSecrets }}
      {{- end }}
