name: Docs

on:
  push:
    branches: ["main"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

jobs:
  # Copy Documentation to the gh-pages branch
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updating Documentation from `main`"
          branch: gh-pages
          file_pattern: "docs/*.md"

